<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Бестиарий роботов – Проект Гелиос</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ade000faa502ff19940f8f0164ee5c92.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.content { max-width: 900px; }
p { text-indent: 1.5em; margin-top: 0.3em; margin-bottom: 0.3em; text-align: justify; }
h1 + p, h2 + p, h3 + p, h4 + p { text-indent: 0; }
p:has(img), .quarto-figure, .figure { text-indent: 0; }
p:has(> strong:first-child) { text-indent: 0; }
p:has(> em:first-child) { text-indent: 0; }
</style>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Проект Гелиос</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../ru/index.html"> 
<span class="menu-text">Главная</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ru/book/index.html"> 
<span class="menu-text">Книга</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../ru/science/index.html" aria-current="page"> 
<span class="menu-text">Наука</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../ru/about.html"> 
<span class="menu-text">Об авторе</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../"> 
<span class="menu-text">RU</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../en/"> 
<span class="menu-text">EN</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ru/science/physics.html">Архив (миграция)</a></li><li class="breadcrumb-item"><a href="../../ru/science/robots.html">Бестиарий роботов</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Обзор</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/executive-summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Проект «Гелиос» за 5 минут</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Почему Меркурий?</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Детальные темы</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/mirrors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Зеркала Роя</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/hub.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Хаб приёма энергии</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/delivery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Доставка</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/production.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Производство</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Производство: детали</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/energy-production.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Энергетика производства</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/regolith-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Переработка реголита</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/carbon-extraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Добыча углерода</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/hydraulics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Гидравлика и жидкости</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/batteries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Производство накопителей</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/replication.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Саморепликация</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/factory-interior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Внутреннее устройство фабрики</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Сводные статьи</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/energy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Энергобаланс</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/moon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Луна</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/mercury.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Меркурий</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/mars.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Терраформирование Марса</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/budget.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Бюджет проекта</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/roadmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Дорожная карта</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Справочники</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/risks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Риски и ограничения проекта</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Глоссарий терминов</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/data/constants.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Физические константы</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/data/sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Библиография</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Архив (миграция)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/physics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Физика и инженерия проекта</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/robots.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Бестиарий роботов</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/factory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Завод «Точка Ноль»</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/energy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Расчёты энергии</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/railgun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Масс-драйверы</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../ru/science/calculations/scaling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Масштабирование производства</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#контекст-среды" id="toc-контекст-среды" class="nav-link active" data-scroll-target="#контекст-среды">Контекст среды</a></li>
  <li><a href="#логика-эволюции-поколений" id="toc-логика-эволюции-поколений" class="nav-link" data-scroll-target="#логика-эволюции-поколений">Логика эволюции поколений</a>
  <ul class="collapse">
  <li><a href="#проблема" id="toc-проблема" class="nav-link" data-scroll-target="#проблема">Проблема</a></li>
  <li><a href="#решение" id="toc-решение" class="nav-link" data-scroll-target="#решение">Решение</a></li>
  <li><a href="#результат" id="toc-результат" class="nav-link" data-scroll-target="#результат">Результат</a></li>
  </ul></li>
  <li><a href="#системы-питания" id="toc-системы-питания" class="nav-link" data-scroll-target="#системы-питания">Системы питания</a>
  <ul class="collapse">
  <li><a href="#поколение-1-li-ion-батареи" id="toc-поколение-1-li-ion-батареи" class="nav-link" data-scroll-target="#поколение-1-li-ion-батареи">Поколение 1: Li-Ion батареи</a></li>
  <li><a href="#поколение-2-nas-батареи-местное-производство" id="toc-поколение-2-nas-батареи-местное-производство" class="nav-link" data-scroll-target="#поколение-2-nas-батареи-местное-производство">Поколение 2: NaS батареи (местное производство)</a></li>
  <li><a href="#электромоторы" id="toc-электромоторы" class="nav-link" data-scroll-target="#электромоторы">Электромоторы</a></li>
  </ul></li>
  <li><a href="#поколение-1-земной-импорт" id="toc-поколение-1-земной-импорт" class="nav-link" data-scroll-target="#поколение-1-земной-импорт">Поколение 1 — Земной импорт</a>
  <ul class="collapse">
  <li><a href="#паук-з-spider-z" id="toc-паук-з-spider-z" class="nav-link" data-scroll-target="#паук-з-spider-z">Паук-З (Spider-Z)</a>
  <ul class="collapse">
  <li><a href="#физические-параметры" id="toc-физические-параметры" class="nav-link" data-scroll-target="#физические-параметры">Физические параметры</a></li>
  <li><a href="#состав-материалов" id="toc-состав-материалов" class="nav-link" data-scroll-target="#состав-материалов">Состав материалов</a></li>
  <li><a href="#сенсоры" id="toc-сенсоры" class="nav-link" data-scroll-target="#сенсоры">Сенсоры</a></li>
  <li><a href="#сменные-модули" id="toc-сменные-модули" class="nav-link" data-scroll-target="#сменные-модули">Сменные модули</a></li>
  <li><a href="#конструкция" id="toc-конструкция" class="nav-link" data-scroll-target="#конструкция">Конструкция</a></li>
  </ul></li>
  <li><a href="#краб-з-crab-z" id="toc-краб-з-crab-z" class="nav-link" data-scroll-target="#краб-з-crab-z">Краб-З (Crab-Z)</a>
  <ul class="collapse">
  <li><a href="#физические-параметры-1" id="toc-физические-параметры-1" class="nav-link" data-scroll-target="#физические-параметры-1">Физические параметры</a></li>
  <li><a href="#состав-материалов-1" id="toc-состав-материалов-1" class="nav-link" data-scroll-target="#состав-материалов-1">Состав материалов</a></li>
  <li><a href="#сенсоры-1" id="toc-сенсоры-1" class="nav-link" data-scroll-target="#сенсоры-1">Сенсоры</a></li>
  <li><a href="#сменные-модули-1" id="toc-сменные-модули-1" class="nav-link" data-scroll-target="#сменные-модули-1">Сменные модули</a></li>
  <li><a href="#конструкция-1" id="toc-конструкция-1" class="nav-link" data-scroll-target="#конструкция-1">Конструкция</a></li>
  </ul></li>
  <li><a href="#кентавр-з-centaur-z" id="toc-кентавр-з-centaur-z" class="nav-link" data-scroll-target="#кентавр-з-centaur-z">Кентавр-З (Centaur-Z)</a>
  <ul class="collapse">
  <li><a href="#физические-параметры-2" id="toc-физические-параметры-2" class="nav-link" data-scroll-target="#физические-параметры-2">Физические параметры</a></li>
  <li><a href="#состав-материалов-2" id="toc-состав-материалов-2" class="nav-link" data-scroll-target="#состав-материалов-2">Состав материалов</a></li>
  <li><a href="#сенсоры-2" id="toc-сенсоры-2" class="nav-link" data-scroll-target="#сенсоры-2">Сенсоры</a></li>
  <li><a href="#сменные-модули-2" id="toc-сменные-модули-2" class="nav-link" data-scroll-target="#сменные-модули-2">Сменные модули</a></li>
  <li><a href="#конструкция-2" id="toc-конструкция-2" class="nav-link" data-scroll-target="#конструкция-2">Конструкция</a></li>
  </ul></li>
  <li><a href="#манипулятор-ф-а1-fab-arm-s1" id="toc-манипулятор-ф-а1-fab-arm-s1" class="nav-link" data-scroll-target="#манипулятор-ф-а1-fab-arm-s1">Манипулятор Ф-А1 (Fab-Arm S1)</a>
  <ul class="collapse">
  <li><a href="#физические-параметры-3" id="toc-физические-параметры-3" class="nav-link" data-scroll-target="#физические-параметры-3">Физические параметры</a></li>
  <li><a href="#состав-материалов-3" id="toc-состав-материалов-3" class="nav-link" data-scroll-target="#состав-материалов-3">Состав материалов</a></li>
  <li><a href="#сенсоры-3" id="toc-сенсоры-3" class="nav-link" data-scroll-target="#сенсоры-3">Сенсоры</a></li>
  <li><a href="#сменные-модули-3" id="toc-сменные-модули-3" class="nav-link" data-scroll-target="#сменные-модули-3">Сменные модули</a></li>
  <li><a href="#конструкция-3" id="toc-конструкция-3" class="nav-link" data-scroll-target="#конструкция-3">Конструкция</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#поколение-2-меркурианское-производство" id="toc-поколение-2-меркурианское-производство" class="nav-link" data-scroll-target="#поколение-2-меркурианское-производство">Поколение 2 — Меркурианское производство</a>
  <ul class="collapse">
  <li><a href="#краб-м-crab-m" id="toc-краб-м-crab-m" class="nav-link" data-scroll-target="#краб-м-crab-m">Краб-М (Crab-M)</a>
  <ul class="collapse">
  <li><a href="#физические-параметры-4" id="toc-физические-параметры-4" class="nav-link" data-scroll-target="#физические-параметры-4">Физические параметры</a></li>
  <li><a href="#состав-материалов-4" id="toc-состав-материалов-4" class="nav-link" data-scroll-target="#состав-материалов-4">Состав материалов</a></li>
  <li><a href="#сенсоры-4" id="toc-сенсоры-4" class="nav-link" data-scroll-target="#сенсоры-4">Сенсоры</a></li>
  <li><a href="#сменные-модули-4" id="toc-сменные-модули-4" class="nav-link" data-scroll-target="#сменные-модули-4">Сменные модули</a></li>
  <li><a href="#конструкция-4" id="toc-конструкция-4" class="nav-link" data-scroll-target="#конструкция-4">Конструкция</a></li>
  </ul></li>
  <li><a href="#кентавр-м-centaur-m" id="toc-кентавр-м-centaur-m" class="nav-link" data-scroll-target="#кентавр-м-centaur-m">Кентавр-М (Centaur-M)</a>
  <ul class="collapse">
  <li><a href="#физические-параметры-5" id="toc-физические-параметры-5" class="nav-link" data-scroll-target="#физические-параметры-5">Физические параметры</a></li>
  <li><a href="#состав-материалов-5" id="toc-состав-материалов-5" class="nav-link" data-scroll-target="#состав-материалов-5">Состав материалов</a></li>
  <li><a href="#сенсоры-5" id="toc-сенсоры-5" class="nav-link" data-scroll-target="#сенсоры-5">Сенсоры</a></li>
  <li><a href="#конструкция-5" id="toc-конструкция-5" class="nav-link" data-scroll-target="#конструкция-5">Конструкция</a></li>
  </ul></li>
  <li><a href="#крот-м-mole-m" id="toc-крот-м-mole-m" class="nav-link" data-scroll-target="#крот-м-mole-m">Крот-М (Mole-M)</a>
  <ul class="collapse">
  <li><a href="#физические-параметры-6" id="toc-физические-параметры-6" class="nav-link" data-scroll-target="#физические-параметры-6">Физические параметры</a></li>
  <li><a href="#состав-материалов-6" id="toc-состав-материалов-6" class="nav-link" data-scroll-target="#состав-материалов-6">Состав материалов</a></li>
  <li><a href="#сенсоры-6" id="toc-сенсоры-6" class="nav-link" data-scroll-target="#сенсоры-6">Сенсоры</a></li>
  <li><a href="#сменные-модули-5" id="toc-сменные-модули-5" class="nav-link" data-scroll-target="#сменные-модули-5">Сменные модули</a></li>
  <li><a href="#конструкция-6" id="toc-конструкция-6" class="nav-link" data-scroll-target="#конструкция-6">Конструкция</a></li>
  </ul></li>
  <li><a href="#операционная-модель-крот-м" id="toc-операционная-модель-крот-м" class="nav-link" data-scroll-target="#операционная-модель-крот-м">Операционная модель Крот-М</a>
  <ul class="collapse">
  <li><a href="#проблема-энергопитание-при-88-суточной-ночи" id="toc-проблема-энергопитание-при-88-суточной-ночи" class="nav-link" data-scroll-target="#проблема-энергопитание-при-88-суточной-ночи">Проблема: энергопитание при 88-суточной ночи</a></li>
  <li><a href="#физика-терминатора-меркурия" id="toc-физика-терминатора-меркурия" class="nav-link" data-scroll-target="#физика-терминатора-меркурия">Физика терминатора Меркурия</a></li>
  <li><a href="#рекомендованное-решение-гибрид-кабель-батарея" id="toc-рекомендованное-решение-гибрид-кабель-батарея" class="nav-link" data-scroll-target="#рекомендованное-решение-гибрид-кабель-батарея">Рекомендованное решение: ГИБРИД (кабель + батарея)</a></li>
  <li><a href="#параметры-кабельной-системы" id="toc-параметры-кабельной-системы" class="nav-link" data-scroll-target="#параметры-кабельной-системы">Параметры кабельной системы</a></li>
  <li><a href="#схема-добычи-комбинированная" id="toc-схема-добычи-комбинированная" class="nav-link" data-scroll-target="#схема-добычи-комбинированная">Схема добычи: комбинированная</a></li>
  <li><a href="#масштабируемость-1000-заводов" id="toc-масштабируемость-1000-заводов" class="nav-link" data-scroll-target="#масштабируемость-1000-заводов">Масштабируемость (1000 заводов)</a></li>
  </ul></li>
  <li><a href="#операционная-модель-краб-м" id="toc-операционная-модель-краб-м" class="nav-link" data-scroll-target="#операционная-модель-краб-м">Операционная модель Краб-М</a>
  <ul class="collapse">
  <li><a href="#проблема-логистика-по-маршрутам-разной-длины" id="toc-проблема-логистика-по-маршрутам-разной-длины" class="nav-link" data-scroll-target="#проблема-логистика-по-маршрутам-разной-длины">Проблема: логистика по маршрутам разной длины</a></li>
  <li><a href="#рекомендованное-решение-зарядные-станции" id="toc-рекомендованное-решение-зарядные-станции" class="nav-link" data-scroll-target="#рекомендованное-решение-зарядные-станции">Рекомендованное решение: ЗАРЯДНЫЕ СТАНЦИИ</a></li>
  <li><a href="#параметры-системы-питания" id="toc-параметры-системы-питания" class="nav-link" data-scroll-target="#параметры-системы-питания">Параметры системы питания</a></li>
  <li><a href="#схема-зарядной-сети" id="toc-схема-зарядной-сети" class="nav-link" data-scroll-target="#схема-зарядной-сети">Схема зарядной сети</a></li>
  <li><a href="#инфраструктура-зарядных-станций" id="toc-инфраструктура-зарядных-станций" class="nav-link" data-scroll-target="#инфраструктура-зарядных-станций">Инфраструктура зарядных станций</a></li>
  <li><a href="#время-цикла-с-зарядкой" id="toc-время-цикла-с-зарядкой" class="nav-link" data-scroll-target="#время-цикла-с-зарядкой">Время цикла с зарядкой</a></li>
  <li><a href="#количество-крабов-м-на-комплекс" id="toc-количество-крабов-м-на-комплекс" class="nav-link" data-scroll-target="#количество-крабов-м-на-комплекс">Количество Крабов-М на комплекс</a></li>
  <li><a href="#логистика-графита-комплексы-карбон" id="toc-логистика-графита-комплексы-карбон" class="nav-link" data-scroll-target="#логистика-графита-комплексы-карбон">Логистика графита (комплексы Карбон)</a></li>
  </ul></li>
  <li><a href="#операционная-модель-кентавр-м" id="toc-операционная-модель-кентавр-м" class="nav-link" data-scroll-target="#операционная-модель-кентавр-м">Операционная модель Кентавр-М</a>
  <ul class="collapse">
  <li><a href="#проблема-работа-в-двух-зонах" id="toc-проблема-работа-в-двух-зонах" class="nav-link" data-scroll-target="#проблема-работа-в-двух-зонах">Проблема: работа в двух зонах</a></li>
  <li><a href="#рекомендованное-решение-кабель-автономия" id="toc-рекомендованное-решение-кабель-автономия" class="nav-link" data-scroll-target="#рекомендованное-решение-кабель-автономия">Рекомендованное решение: КАБЕЛЬ + АВТОНОМИЯ</a></li>
  <li><a href="#параметры-системы-питания-1" id="toc-параметры-системы-питания-1" class="nav-link" data-scroll-target="#параметры-системы-питания-1">Параметры системы питания</a></li>
  <li><a href="#схема-работы-снаружи-вахтовый-режим" id="toc-схема-работы-снаружи-вахтовый-режим" class="nav-link" data-scroll-target="#схема-работы-снаружи-вахтовый-режим">Схема работы снаружи (вахтовый режим)</a></li>
  <li><a href="#кабельная-система-внутри-купола" id="toc-кабельная-система-внутри-купола" class="nav-link" data-scroll-target="#кабельная-система-внутри-купола">Кабельная система внутри купола</a></li>
  <li><a href="#зарядные-станции-снаружи" id="toc-зарядные-станции-снаружи" class="nav-link" data-scroll-target="#зарядные-станции-снаружи">Зарядные станции снаружи</a></li>
  <li><a href="#распределение-кентавров-м-по-зонам" id="toc-распределение-кентавров-м-по-зонам" class="nav-link" data-scroll-target="#распределение-кентавров-м-по-зонам">Распределение Кентавров-М по зонам</a></li>
  </ul></li>
  <li><a href="#сводка-энергоснабжение-всех-gen-2-роботов" id="toc-сводка-энергоснабжение-всех-gen-2-роботов" class="nav-link" data-scroll-target="#сводка-энергоснабжение-всех-gen-2-роботов">Сводка: энергоснабжение всех Gen-2 роботов</a>
  <ul class="collapse">
  <li><a href="#таблица-решений" id="toc-таблица-решений" class="nav-link" data-scroll-target="#таблица-решений">Таблица решений</a></li>
  <li><a href="#инфраструктура-на-1-комплекс" id="toc-инфраструктура-на-1-комплекс" class="nav-link" data-scroll-target="#инфраструктура-на-1-комплекс">Инфраструктура на 1 комплекс</a></li>
  <li><a href="#пересчёт-количества-роботов" id="toc-пересчёт-количества-роботов" class="nav-link" data-scroll-target="#пересчёт-количества-роботов">Пересчёт количества роботов</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#монтажная-бригада-the-landing-party" id="toc-монтажная-бригада-the-landing-party" class="nav-link" data-scroll-target="#монтажная-бригада-the-landing-party">Монтажная Бригада (The Landing Party)</a>
  <ul class="collapse">
  <li><a href="#пауки-16" id="toc-пауки-16" class="nav-link" data-scroll-target="#пауки-16">Пауки × 16</a></li>
  <li><a href="#крабы-12" id="toc-крабы-12" class="nav-link" data-scroll-target="#крабы-12">Крабы × 12</a></li>
  <li><a href="#кентавры-24" id="toc-кентавры-24" class="nav-link" data-scroll-target="#кентавры-24">Кентавры × 24</a></li>
  <li><a href="#кроты-4" id="toc-кроты-4" class="nav-link" data-scroll-target="#кроты-4">Кроты × 4</a></li>
  <li><a href="#кого-не-везём" id="toc-кого-не-везём" class="nav-link" data-scroll-target="#кого-не-везём">Кого НЕ везём</a></li>
  <li><a href="#визуализация-высадки" id="toc-визуализация-высадки" class="nav-link" data-scroll-target="#визуализация-высадки">Визуализация высадки</a></li>
  <li><a href="#итого-56-роботов" id="toc-итого-56-роботов" class="nav-link" data-scroll-target="#итого-56-роботов">Итого: 56 роботов</a></li>
  </ul></li>
  <li><a href="#известные-ограничения-роботов" id="toc-известные-ограничения-роботов" class="nav-link" data-scroll-target="#известные-ограничения-роботов">Известные ограничения роботов</a>
  <ul class="collapse">
  <li><a href="#высокие-проблемы" id="toc-высокие-проблемы" class="nav-link" data-scroll-target="#высокие-проблемы">Высокие проблемы</a>
  <ul class="collapse">
  <li><a href="#смазка-при-430c" id="toc-смазка-при-430c" class="nav-link" data-scroll-target="#смазка-при-430c">1. Смазка при +430°C</a></li>
  <li><a href="#тепловой-режим-nas-батарей" id="toc-тепловой-режим-nas-батарей" class="nav-link" data-scroll-target="#тепловой-режим-nas-батарей">2. Тепловой режим NaS-батарей</a></li>
  <li><a href="#вероятность-отказов-недооценена" id="toc-вероятность-отказов-недооценена" class="nav-link" data-scroll-target="#вероятность-отказов-недооценена">3. Вероятность отказов недооценена</a></li>
  </ul></li>
  <li><a href="#требуют-исследования" id="toc-требуют-исследования" class="nav-link" data-scroll-target="#требуют-исследования">Требуют исследования</a>
  <ul class="collapse">
  <li><a href="#пылезащита-в-вакууме" id="toc-пылезащита-в-вакууме" class="nav-link" data-scroll-target="#пылезащита-в-вакууме">4. Пылезащита в вакууме</a></li>
  <li><a href="#автономность-при-670-секундной-задержке" id="toc-автономность-при-670-секундной-задержке" class="nav-link" data-scroll-target="#автономность-при-670-секундной-задержке">5. Автономность при 670-секундной задержке</a></li>
  <li><a href="#ремонтопригодность-gen-1" id="toc-ремонтопригодность-gen-1" class="nav-link" data-scroll-target="#ремонтопригодность-gen-1">6. Ремонтопригодность Gen-1</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../ru/science/physics.html">Архив (миграция)</a></li><li class="breadcrumb-item"><a href="../../ru/science/robots.html">Бестиарий роботов</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Бестиарий роботов</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Проект:</strong> Helios Prime <strong>Документ:</strong> Манифест робототехники и эволюции <strong>Версия:</strong> 6.0</p>
<hr>
<blockquote class="blockquote">
<p><strong>TL;DR</strong></p>
<ul>
<li><strong>Два поколения:</strong> Gen-1 (земной импорт, титан/карбон) и Gen-2 (меркурианское производство, <strong>гибрид Fe/Al</strong>)</li>
<li><strong>5 классов Gen-1:</strong> Паук-З (разведчик), Краб-З (грузчик), Кентавр-З (техник), Манипулятор Ф-А1 (стационарный), Крот-З (экскаватор)</li>
<li><strong>3 класса Gen-2:</strong> Краб-М (~1000 кг), Кентавр-М (~370 кг), Крот-М (~1500 кг) — <strong>гибрид Fe (критические узлы) + Al (рама, корпус)</strong>, на 97% из локальных материалов</li>
<li><strong>«Витамины»:</strong> 1–3% массы робота (CPU, сенсоры, обмотки моторов) импортируется с Земли</li>
<li><strong>Первая экспедиция:</strong> 56 роботов (16 Пауков + 12 Крабов + 24 Кентавра + 4 Крота) собирают завод за 7 дней</li>
<li><strong>Сборочный стапель:</strong> 10 параллельных позиций → 5 роботов/день</li>
<li><strong>Материальный баланс:</strong> Al экономим для зеркал → сталь только для критических узлов (колёса, гусеницы, ковш)</li>
</ul>
</blockquote>
<hr>
<section id="контекст-среды" class="level2">
<h2 class="anchored" data-anchor-id="контекст-среды">Контекст среды</h2>
<p><strong>Локация:</strong> Меркурий, Северный полюс, кратер Прокофьева</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Параметр</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Гравитация</td>
<td style="text-align: left;">0.38g (3.7 м/с²)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Атмосфера</td>
<td style="text-align: left;">Отсутствует (жёсткий вакуум)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Температура (тень)</td>
<td style="text-align: left;">−180°C</td>
</tr>
<tr class="even">
<td style="text-align: left;">Температура (солнце)</td>
<td style="text-align: left;">+430°C</td>
</tr>
</tbody>
</table>
<p><strong>Условия поверхности:</strong> - Реголитовая пыль крайне абразивна, электростатически заряжена, острая как стекло - Отсутствие выветривания — камни режут как бритва - Нет коррозии, но есть термоциклирование и радиация</p>
<hr>
</section>
<section id="логика-эволюции-поколений" class="level2">
<h2 class="anchored" data-anchor-id="логика-эволюции-поколений">Логика эволюции поколений</h2>
<section id="проблема" class="level3">
<h3 class="anchored" data-anchor-id="проблема">Проблема</h3>
<p>Земные материалы (карбон, кевлар, тефлон) невозможно производить на Меркурии без сложных химических заводов. Импортировать их слишком дорого.</p>
</section>
<section id="решение" class="level3">
<h3 class="anchored" data-anchor-id="решение">Решение</h3>
<p>Локальные роботы должны строиться из элементов, доступных в реголите: - Железо (Fe) - Кремний (Si) - Сера (S) - Алюминий (Al) - Титан (Ti)</p>
</section>
<section id="результат" class="level3">
<h3 class="anchored" data-anchor-id="результат">Результат</h3>
<p>Роботы <strong>Поколения 2</strong> используют <strong>гибридную конструкцию Fe/Al</strong> — оптимизация под дефицит алюминия (нужен для зеркал) и избыток железа:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Компонент</th>
<th>Материал</th>
<th>Обоснование</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Рама/шасси</td>
<td><strong>Сталь</strong></td>
<td>Прочность, железо доступно (18 т/день)</td>
</tr>
<tr class="even">
<td>Ноги/колёса</td>
<td><strong>Сталь</strong></td>
<td>Абразивостойкость к реголиту</td>
</tr>
<tr class="odd">
<td>Корпус/панели</td>
<td>Алюминий</td>
<td>Радиаторы, защита от перегрева</td>
</tr>
<tr class="even">
<td>Манипуляторы</td>
<td>Алюминий</td>
<td>Точность, лёгкость рук</td>
</tr>
</tbody>
</table>
<p><strong>Преимущества гибрида:</strong> - <strong>Экономия Al</strong> — ~4 т/день на роботов вместо ~8 т (остальное на зеркала!) - <strong>Использование Fe</strong> — 12 т/день (ранее почти не использовался) - <strong>Прочность</strong> — стальная рама выдерживает нагрузки лучше алюминия - <strong>Абразивостойкость</strong> — стальные колёса служат дольше в агрессивном реголите</p>
<hr>
</section>
</section>
<section id="системы-питания" class="level2">
<h2 class="anchored" data-anchor-id="системы-питания">Системы питания</h2>
<section id="поколение-1-li-ion-батареи" class="level3">
<h3 class="anchored" data-anchor-id="поколение-1-li-ion-батареи">Поколение 1: Li-Ion батареи</h3>
<p>Все мобильные роботы Поколения 1 используют <strong>литий-ионные аккумуляторы</strong> (Li-Ion), доставленные с Земли:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Характеристика</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Тип</td>
<td style="text-align: left;">Li-Ion (литий-железо-фосфат, LiFePO₄)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Энергоёмкость</td>
<td style="text-align: left;">150–200 Вт·ч/кг</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Рабочая температура</td>
<td style="text-align: left;">−20°C до +60°C</td>
</tr>
<tr class="even">
<td style="text-align: left;">Термозащита</td>
<td style="text-align: left;">Активный термоконтроль (нагреватели в тени, радиаторы на солнце)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Зарядка</td>
<td style="text-align: left;">От солнечных панелей или зарядных станций на базе</td>
</tr>
</tbody>
</table>
<p><strong>Примечание:</strong> Стационарные роботы (Манипулятор Ф-А1) питаются от сети базы.</p>
</section>
<section id="поколение-2-nas-батареи-местное-производство" class="level3">
<h3 class="anchored" data-anchor-id="поколение-2-nas-батареи-местное-производство">Поколение 2: NaS батареи (местное производство)</h3>
<p>Роботы Поколения 2 используют <strong>натрий-серные аккумуляторы</strong> (NaS), произведённые на Меркурии:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Характеристика</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Тип</td>
<td style="text-align: left;">NaS (натрий-серная батарея)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Энергоёмкость</td>
<td style="text-align: left;">100–150 Вт·ч/кг</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Рабочая температура</td>
<td style="text-align: left;">+300°C (требует подогрева)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Преимущество</td>
<td style="text-align: left;">Сера и натрий добываются из реголита</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Срок службы</td>
<td style="text-align: left;">2500+ циклов</td>
</tr>
</tbody>
</table>
<p><strong>Почему NaS:</strong> - Не требует лития (которого нет на Меркурии) - Сера — побочный продукт переработки руды - Натрий доступен в реголите - Высокая температура работы — не проблема на солнечной стороне</p>
<blockquote class="blockquote">
<p><strong>Производство NaS батарей:</strong> <a href="../../ru/science/factory.html#этап-6-натрий-серные-аккумуляторы-nas">Завод «Точка Ноль» — Этап 6</a></p>
</blockquote>
</section>
<section id="электромоторы" class="level3">
<h3 class="anchored" data-anchor-id="электромоторы">Электромоторы</h3>
<p>Все роботы используют <strong>бесщёточные электродвигатели</strong> (BLDC):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Поколение</th>
<th style="text-align: left;">Материалы</th>
<th style="text-align: left;">Особенности</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gen 1</td>
<td style="text-align: left;">Медные обмотки, неодимовые магниты</td>
<td style="text-align: left;">Высокий КПД, точное управление</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gen 2</td>
<td style="text-align: left;">Алюминиевые обмотки, ферритовые магниты</td>
<td style="text-align: left;">Тяжелее, но из местных материалов</td>
</tr>
</tbody>
</table>
<p><strong>«Витамины» для Gen 2:</strong> Контроллеры моторов и обмотки из меди/серебра импортируются с Земли (1–2% массы робота).</p>
<hr>
</section>
</section>
<section id="поколение-1-земной-импорт" class="level1">
<h1>Поколение 1 — Земной импорт</h1>
<p><em>Высокотехнологичные юниты, собранные на Земле. Оптимизированы по массе для запуска. Дорогие, точные, хрупкие. Используют «мягкую» защиту (ткани).</em></p>
<p><strong>Визуальный стиль:</strong> NASA/SpaceX — белые керамические плиты, золотая фольга (MLI), серые кевларовые гетры, чистые линии, синие/белые индикаторы.</p>
<hr>
<section id="паук-з-spider-z" class="level2">
<h2 class="anchored" data-anchor-id="паук-з-spider-z">Паук-З (Spider-Z)</h2>
<p><em>Разведчик / Высотный альпинист</em></p>
<section id="физические-параметры" class="level3">
<h3 class="anchored" data-anchor-id="физические-параметры">Физические параметры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Параметр</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Вес (сухой)</td>
<td style="text-align: left;">82 кг</td>
</tr>
<tr class="even">
<td style="text-align: left;">Вес на Меркурии</td>
<td style="text-align: left;">31 кг (ощущаемый)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Габариты (сложен)</td>
<td style="text-align: left;">1.2 × 1.2 × 0.4 м</td>
</tr>
<tr class="even">
<td style="text-align: left;">Высота (рабочая)</td>
<td style="text-align: left;">до 1.5 м</td>
</tr>
</tbody>
</table>
</section>
<section id="состав-материалов" class="level3">
<h3 class="anchored" data-anchor-id="состав-материалов">Состав материалов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Источник</th>
<th style="text-align: left;">Масса</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Земной импорт</td>
<td style="text-align: left;">82 кг (100%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Локальные ресурсы</td>
<td style="text-align: left;">0 кг</td>
</tr>
</tbody>
</table>
<p><strong>Разбивка:</strong> - Титановый сплав (3D-печатный скелет): 40 кг - Керамика из оксида алюминия (броня): 20 кг - Актуаторы и моторы (высокоточные): 15 кг - Батареи (Li-Ion): 5 кг - Электроника и золотая фольга: 2 кг</p>
</section>
<section id="сенсоры" class="level3">
<h3 class="anchored" data-anchor-id="сенсоры">Сенсоры</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Тип</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Визуальные</td>
<td style="text-align: left;">Кольцевой обзор 360°, 4 пары стереокамер по периметру за сапфировым стеклом</td>
</tr>
<tr class="even">
<td style="text-align: left;">Лидар</td>
<td style="text-align: left;">Выдвижная башенка на спине (VLP-16) для 3D-картографирования скал</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Тактильные</td>
<td style="text-align: left;">Пьезодатчики давления в каждом когте (чувствуют, крошится ли камень)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Тепловизор</td>
<td style="text-align: left;">ИК-камера спереди для поиска «холодных троп» в тени</td>
</tr>
</tbody>
</table>
</section>
<section id="сменные-модули" class="level3">
<h3 class="anchored" data-anchor-id="сменные-модули">Сменные модули</h3>
<p><strong>Крепление:</strong> Спинная рельса с контактами питания</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Модуль</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Катушка кабеля</td>
<td style="text-align: left;">500 м силового кабеля (базовый)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Зеркало гелиостата</td>
<td style="text-align: left;">Складной веер для установки на пиках</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ретранслятор связи</td>
<td style="text-align: left;">Антенна-штырь</td>
</tr>
<tr class="even">
<td style="text-align: left;">Бур для анкеров</td>
<td style="text-align: left;">С магазином на 50 дюбелей</td>
</tr>
</tbody>
</table>
</section>
<section id="конструкция" class="level3">
<h3 class="anchored" data-anchor-id="конструкция">Конструкция</h3>
<p><strong>Корпус:</strong> - Плоский шестиугольный центральный хаб, низкий профиль - Спереди и сзади — массивные стыковочные замки (электромагниты) - Материал: белая матовая керамика поверх титана - Размер: диаметр 0.5 м, толщина 0.2 м</p>
<p><strong>Ноги:</strong> - 6 многосуставных ног, расходящихся радиально - Длина ноги: 0.8–1.0 м, толщина: 8–10 см - Материал: титановый скелет, частично в золотой фольге</p>
<p><strong>Суставы:</strong> - Верхние («колени»): закрыты золотистыми гофрами (MLI) - Нижние («лодыжки»): открытый металлический узел с зубьями - Размер гофр: диаметр 12–15 см</p>
<p><strong>Когти:</strong> - Материал: карбид вольфрама - 3 острых загнутых когтя + микро-плазменный бур в центре</p>
<hr>
</section>
</section>
<section id="краб-з-crab-z" class="level2">
<h2 class="anchored" data-anchor-id="краб-з-crab-z">Краб-З (Crab-Z)</h2>
<p><em>Тяжёлый грузчик / Логист</em></p>
<section id="физические-параметры-1" class="level3">
<h3 class="anchored" data-anchor-id="физические-параметры-1">Физические параметры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Параметр</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Вес (сухой)</td>
<td style="text-align: left;">950 кг</td>
</tr>
<tr class="even">
<td style="text-align: left;">Вес на Меркурии</td>
<td style="text-align: left;">361 кг (ощущаемый)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Длина</td>
<td style="text-align: left;">4.5 м</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ширина</td>
<td style="text-align: left;">4.2 м</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Высота</td>
<td style="text-align: left;">1.5–4.0 м (изменяемая)</td>
</tr>
</tbody>
</table>
</section>
<section id="состав-материалов-1" class="level3">
<h3 class="anchored" data-anchor-id="состав-материалов-1">Состав материалов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Источник</th>
<th style="text-align: left;">Масса</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Земной импорт</td>
<td style="text-align: left;">950 кг (100%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Локальные ресурсы</td>
<td style="text-align: left;">0 кг</td>
</tr>
</tbody>
</table>
<p><strong>Разбивка:</strong> - Алюминиево-литиевый сплав (ферменная рама): 600 кг - Пружинная сталь / Нитинол (колёса): 200 кг - Актуаторы и лебёдочная система: 80 кг - Батареи (Li-Ion): 40 кг - Электроника и керамика: 30 кг</p>
</section>
<section id="сенсоры-1" class="level3">
<h3 class="anchored" data-anchor-id="сенсоры-1">Сенсоры</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Тип</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Визуальные</td>
<td style="text-align: left;">4 навигационные стереокамеры на каждой ноге (смотрят на колёса)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Лидар</td>
<td style="text-align: left;">2 дальнобойных лидара на передней и задней арке</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Датчики нагрузки</td>
<td style="text-align: left;">Тензодатчики в лебёдках (взвешивание груза в реальном времени)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Сближение</td>
<td style="text-align: left;">Радар снизу для точного захвата контейнера</td>
</tr>
</tbody>
</table>
</section>
<section id="сменные-модули-1" class="level3">
<h3 class="anchored" data-anchor-id="сменные-модули-1">Сменные модули</h3>
<p><strong>Крепление:</strong> Нижняя грузовая палуба с 4 лебёдками</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Модуль</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Спредер</td>
<td style="text-align: left;">Рама для стандартных контейнеров (основной)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Электромагнит</td>
<td style="text-align: left;">Для переноски слитков металла</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Клешня</td>
<td style="text-align: left;">Механический захват для нестандартных грузов</td>
</tr>
<tr class="even">
<td style="text-align: left;">Отвал</td>
<td style="text-align: left;">Бульдозерный, навешивается спереди на раму</td>
</tr>
</tbody>
</table>
</section>
<section id="конструкция-1" class="level3">
<h3 class="anchored" data-anchor-id="конструкция-1">Конструкция</h3>
<p><strong>Рама:</strong> - Высокая П-образная арка (портал) - Ферменная, ажурная, но мощная - Размер: высота 3.5 м, ширина 4 м, балки 20–30 см - Материал: алюминиевые трубы в белых термоодеялах</p>
<p><strong>Колёса:</strong> - Тип: безвоздушные сетчатые (Tweel) - Диаметр: 1.8–2.0 м, ширина: 0.6 м - Материал: блестящая пружинная сталь (нитинол) - Прозрачная структура из проволоки, без воздуха внутри</p>
<p><strong>Телескопические ноги:</strong> - Вертикальные стойки над каждым колесом - Полностью скрыты под серой кевларовой гармошкой - Диаметр чехла: 0.5 м</p>
<p><strong>Ступицы:</strong> - Гладкие керамические купола (герметичные)</p>
<hr>
</section>
</section>
<section id="кентавр-з-centaur-z" class="level2">
<h2 class="anchored" data-anchor-id="кентавр-з-centaur-z">Кентавр-З (Centaur-Z)</h2>
<p><em>Мобильный техник / Ремонтник</em></p>
<section id="физические-параметры-2" class="level3">
<h3 class="anchored" data-anchor-id="физические-параметры-2">Физические параметры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Параметр</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Вес (сухой)</td>
<td style="text-align: left;">150 кг</td>
</tr>
<tr class="even">
<td style="text-align: left;">Вес на Меркурии</td>
<td style="text-align: left;">57 кг (ощущаемый)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Длина</td>
<td style="text-align: left;">1.8 м</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ширина</td>
<td style="text-align: left;">1.4 м</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Высота</td>
<td style="text-align: left;">1.6 м</td>
</tr>
</tbody>
</table>
</section>
<section id="состав-материалов-2" class="level3">
<h3 class="anchored" data-anchor-id="состав-материалов-2">Состав материалов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Источник</th>
<th style="text-align: left;">Масса</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Земной импорт</td>
<td style="text-align: left;">150 кг (100%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Локальные ресурсы</td>
<td style="text-align: left;">0 кг</td>
</tr>
</tbody>
</table>
<p><strong>Разбивка:</strong> - Карбоновый корпус: 60 кг - Точные моторы и руки: 50 кг - Батареи (Li-Ion): 30 кг - Сенсоры и CPU: 10 кг</p>
</section>
<section id="сенсоры-2" class="level3">
<h3 class="anchored" data-anchor-id="сенсоры-2">Сенсоры</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Тип</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Голова</td>
<td style="text-align: left;">Бинокулярная система камер высокого разрешения («глаза»)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Запястья</td>
<td style="text-align: left;">Микроскопические камеры для точного наведения инструмента</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Грудь</td>
<td style="text-align: left;">Лазерный сканер штрих-кодов и дефектоскопии</td>
</tr>
<tr class="even">
<td style="text-align: left;">Тактильные</td>
<td style="text-align: left;">Датчики усилия в каждом приводе (чувствует сопротивление гайки)</td>
</tr>
</tbody>
</table>
</section>
<section id="сменные-модули-2" class="level3">
<h3 class="anchored" data-anchor-id="сменные-модули-2">Сменные модули</h3>
<p><strong>Крепление:</strong> Разъём «Hex-Click» на запястьях + магазин на поясе</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Модуль</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Трёхпалый захват</td>
<td style="text-align: left;">Универсальный (базовый)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Импульсный гайковёрт</td>
<td style="text-align: left;">Высокий момент</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Лазерная сварка</td>
<td style="text-align: left;">Сварочная головка</td>
</tr>
<tr class="even">
<td style="text-align: left;">Вакуумная присоска</td>
<td style="text-align: left;">Для гладких панелей</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Щуп-диагност</td>
<td style="text-align: left;">Мультиметр</td>
</tr>
</tbody>
</table>
</section>
<section id="конструкция-2" class="level3">
<h3 class="anchored" data-anchor-id="конструкция-2">Конструкция</h3>
<p><strong>Шасси:</strong> - 6-колёсная тележка-ровер (как Curiosity) - Размер: 1.5 × 1.2 м, высота 0.5 м - Материал: композиты, металл</p>
<p><strong>Торс:</strong> - Вращающаяся вертикальная башня - Высота: 0.8 м - Материал: карбон под белыми панелями</p>
<p><strong>Руки:</strong> - 2 манипулятора, 7 степеней свободы - Длина: 1.0–1.2 м - Полностью закрыты серыми надутыми рукавами (тефлоновая ткань)</p>
<p><strong>Голова:</strong> - Блок камер на выдвижной штанге - 2 объектива-глаза - Размер: как коробка из-под обуви - Материал: стекло, металл, золото</p>
<hr>
</section>
</section>
<section id="манипулятор-ф-а1-fab-arm-s1" class="level2">
<h2 class="anchored" data-anchor-id="манипулятор-ф-а1-fab-arm-s1">Манипулятор Ф-А1 (Fab-Arm S1)</h2>
<p><em>Стационарный производственный юнит</em></p>
<section id="физические-параметры-3" class="level3">
<h3 class="anchored" data-anchor-id="физические-параметры-3">Физические параметры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Параметр</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Вес (сухой)</td>
<td style="text-align: left;">250 кг</td>
</tr>
<tr class="even">
<td style="text-align: left;">Вес на Меркурии</td>
<td style="text-align: left;">95 кг (ощущаемый)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Диаметр основания</td>
<td style="text-align: left;">0.8 м</td>
</tr>
<tr class="even">
<td style="text-align: left;">Высота</td>
<td style="text-align: left;">2.5 м</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Радиус досягаемости</td>
<td style="text-align: left;">3.0 м</td>
</tr>
</tbody>
</table>
</section>
<section id="состав-материалов-3" class="level3">
<h3 class="anchored" data-anchor-id="состав-материалов-3">Состав материалов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Источник</th>
<th style="text-align: left;">Масса</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Земной импорт</td>
<td style="text-align: left;">250 кг (100%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Локальные ресурсы</td>
<td style="text-align: left;">0 кг</td>
</tr>
</tbody>
</table>
<p><strong>Разбивка:</strong> - Литое алюминиевое основание: 100 кг - Высокомоментные сервоприводы: 100 кг - Электроника и проводка: 50 кг</p>
</section>
<section id="сенсоры-3" class="level3">
<h3 class="anchored" data-anchor-id="сенсоры-3">Сенсоры</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Тип</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Камера на запястье</td>
<td style="text-align: left;">«Глаз в руке» для точного позиционирования</td>
</tr>
<tr class="even">
<td style="text-align: left;">Датчик силы/момента</td>
<td style="text-align: left;">На фланце (чувствует, если деталь не встаёт на место)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Лазерный сканер</td>
<td style="text-align: left;">Лазерная триангуляция зоны работы (Safety curtain)</td>
</tr>
</tbody>
</table>
</section>
<section id="сменные-модули-3" class="level3">
<h3 class="anchored" data-anchor-id="сменные-модули-3">Сменные модули</h3>
<p><strong>Крепление:</strong> Промышленный фланец ISO</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Модуль</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Горелка</td>
<td style="text-align: left;">Дуговая сварка</td>
</tr>
<tr class="even">
<td style="text-align: left;">Вакуумный захват</td>
<td style="text-align: left;">Для панелей</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Пальцевой захват</td>
<td style="text-align: left;">Для деталей</td>
</tr>
<tr class="even">
<td style="text-align: left;">Шпиндель</td>
<td style="text-align: left;">Фрезеровка</td>
</tr>
</tbody>
</table>
</section>
<section id="конструкция-3" class="level3">
<h3 class="anchored" data-anchor-id="конструкция-3">Конструкция</h3>
<p><strong>Основание:</strong> - Тяжёлая круглая тумба, привинченная болтами к полу - Диаметр: 0.8 м - Цвет: жёлтый/оранжевый</p>
<p><strong>Плечи:</strong> - 2 массивных рычага с поворотными шарнирами - Длина плеча: 1.5 м - Материал: литой алюминий, гладкая краска</p>
<p><strong>Запястье:</strong> - Сложный поворотный узел - Размер: 20 см - Кабельные жгуты</p>
<p><strong>Особенность:</strong> Работает <em>внутри</em> герметичного купола в чистой среде. Суставы открыты или под лёгкими пластиковыми кожухами (как Kuka/Fanuc, но в бело-золотых цветах).</p>
<hr>
</section>
</section>
</section>
<section id="поколение-2-меркурианское-производство" class="level1">
<h1>Поколение 2 — Меркурианское производство</h1>
<p><em>Массово производимые юниты, построенные на Меркурии. Оптимизированы под <strong>гибридную конструкцию Fe/Al</strong> — сталь для несущих частей (рама, ноги), алюминий для корпуса и манипуляторов. Используют «жёсткую» защиту (стальная чешуя на ногах, алюминиевые панели на корпусе).</em></p>
<p><strong>Визуальный стиль:</strong> Промышленный / Космо-индастриал — тёмно-серая стальная рама с видимыми сварными швами WAAM, серебристые алюминиевые панели корпуса, характерная текстура 3D-печати.</p>
<p><strong>Сборка:</strong> 10 параллельных позиций на стапеле → <strong>5 роботов/день</strong> на завод.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Земной прототип: «Тёмные фабрики» Китая (2025)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Концепция полностью автоматизированного производства уже реализована на Земле. В Китае работают <strong>«тёмные фабрики»</strong> (dark factories) — заводы без людей и освещения:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Компания</th>
<th>Площадь</th>
<th>Производительность</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Xiaomi</strong></td>
<td>81 000 м²</td>
<td>10 млн смартфонов/год, 24/7</td>
</tr>
<tr class="even">
<td>Foxconn</td>
<td>—</td>
<td>Заменили 60 000 рабочих роботами</td>
</tr>
<tr class="odd">
<td>BYD</td>
<td>—</td>
<td>Автоматизированная сборка батарей и EV</td>
</tr>
</tbody>
</table>
<p>Китай установил <strong>290 000+ промышленных роботов в 2022</strong> (52% мировых). К 2025 году развёрнуто более <strong>1 миллиона</strong> промышленных роботов.</p>
<p><strong>Источники:</strong></p>
<ul>
<li><a href="https://e.vnexpress.net/news/tech/tech-news/no-lights-no-workers-ai-powered-dark-factories-are-reshaping-china-s-manufacturing-4921224.html">VnExpress: AI-powered dark factories</a></li>
<li><a href="https://www.faf.ae/home/2025/3/19/chinas-dark-factory-revolution-the-rise-of-fully-automated-manufacturing-without-workers-or-lights">Foreign Affairs Forum: Dark Factory Revolution</a></li>
</ul>
</div>
</div>
<p><strong>Материальный баланс:</strong> Al дефицитен (нужен для зеркал), Fe в избытке → роботы на ~70% из стали.</p>
<hr>
<section id="краб-м-crab-m" class="level2">
<h2 class="anchored" data-anchor-id="краб-м-crab-m">Краб-М (Crab-M)</h2>
<p><em>Тяжёлый грузчик / Логист (массовое производство)</em></p>
<section id="физические-параметры-4" class="level3">
<h3 class="anchored" data-anchor-id="физические-параметры-4">Физические параметры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Параметр</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Вес (сухой)</td>
<td style="text-align: left;"><strong>~1 000 кг</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Вес на Меркурии</td>
<td style="text-align: left;">380 кг (ощущаемый)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Длина</td>
<td style="text-align: left;">5.0 м</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ширина</td>
<td style="text-align: left;">4.5 м</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Высота</td>
<td style="text-align: left;">1.5–4.5 м (изменяемая)</td>
</tr>
</tbody>
</table>
</section>
<section id="состав-материалов-4" class="level3">
<h3 class="anchored" data-anchor-id="состав-материалов-4">Состав материалов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Источник</th>
<th style="text-align: left;">Масса</th>
<th style="text-align: left;">Соотношение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Локальные ресурсы</td>
<td style="text-align: left;">~970 кг</td>
<td style="text-align: left;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">«Витамины» (импорт)</td>
<td style="text-align: left;">~30 кг</td>
<td style="text-align: left;">1</td>
</tr>
</tbody>
</table>
<p><strong>Витамины:</strong> - Радиационно-стойкий CPU - Оптические сенсоры (камеры, лидар) - Обмотки электромоторов (медь/серебро) - Капсулы со специализированной смазкой</p>
<p><strong>Локальные материалы (оптимизированный гибрид Fe/Al):</strong> - <strong>Алюминиевая ферменная рама</strong> (350 кг) — лёгкость, достаточная прочность - <strong>Стальные колёса + оси</strong> (300 кг) — абразивостойкость (критично) - Стальные подшипники и узлы (50 кг) - Актуаторы и лебёдочная система (100 кг) - NaS-батарея (натрий-серная, 70 кг) - <strong>Алюминиевые радиаторы и панели корпуса</strong> (100 кг) — теплоотвод</p>
<p><strong>Соотношение:</strong> ~35% сталь, ~45% алюминий, ~20% прочее</p>
</section>
<section id="сенсоры-4" class="level3">
<h3 class="anchored" data-anchor-id="сенсоры-4">Сенсоры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Тип</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Визуальные</td>
<td style="text-align: left;">4 навигационные камеры за толстыми кварцевыми блоками</td>
</tr>
<tr class="even">
<td style="text-align: left;">Лидар</td>
<td style="text-align: left;">Упрощённый, за стальным кожухом</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Датчики нагрузки</td>
<td style="text-align: left;">Тензодатчики в лебёдках</td>
</tr>
<tr class="even">
<td style="text-align: left;">Сближение</td>
<td style="text-align: left;">Радар снизу для точного захвата груза</td>
</tr>
</tbody>
</table>
</section>
<section id="сменные-модули-4" class="level3">
<h3 class="anchored" data-anchor-id="сменные-модули-4">Сменные модули</h3>
<p><strong>Крепление:</strong> Нижняя грузовая палуба с 4 лебёдками</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Модуль</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Спредер</td>
<td style="text-align: left;">Рама для стандартных контейнеров (основной)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Электромагнит</td>
<td style="text-align: left;">Для переноски слитков металла</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Клешня</td>
<td style="text-align: left;">Механический захват для нестандартных грузов</td>
</tr>
<tr class="even">
<td style="text-align: left;">Отвал</td>
<td style="text-align: left;">Бульдозерный, навешивается спереди на раму</td>
</tr>
</tbody>
</table>
</section>
<section id="конструкция-4" class="level3">
<h3 class="anchored" data-anchor-id="конструкция-4">Конструкция</h3>
<p><strong>Рама:</strong> - Высокая П-образная арка (портал) - Ферменная, с характерной текстурой WAAM-печати - Размер: высота 4 м, ширина 4.5 м, балки 20–30 см - Материал: <strong>стальные трубы</strong>, тёмно-серые с видимыми швами</p>
<p><strong>Колёса:</strong> - Тип: безвоздушные с стальными спицами - Диаметр: 2.0 м, ширина: 0.7 м - Материал: <strong>литая сталь</strong> с пружинной структурой — абразивостойкость - Ступицы на стальных подшипниках</p>
<p><strong>Телескопические ноги:</strong> - Вертикальные стойки над каждым колесом - <strong>Стальная чешуя</strong> — защита от абразивного реголита - Диаметр: 0.5 м</p>
<p><strong>Корпус:</strong> - Алюминиевые панели поверх стальной рамы — теплоотвод - Характерный контраст: тёмная сталь + серебристый алюминий</p>
<p><strong>Особенность:</strong> Гибридная конструкция Fe/Al. Стальная рама обеспечивает прочность, алюминиевые панели — теплоотвод. Тяжелее чисто алюминиевого варианта (~1500 vs ~1250 кг), но экономит дефицитный Al для зеркал. Грузоподъёмность до 15 тонн. Основная рабочая лошадка для логистики: доставка зеркал к масс-драйверу, транспортировка модулей и слитков.</p>
<hr>
</section>
</section>
<section id="кентавр-м-centaur-m" class="level2">
<h2 class="anchored" data-anchor-id="кентавр-м-centaur-m">Кентавр-М (Centaur-M)</h2>
<p><em>Сборщик / Манипулятор (массовое производство)</em></p>
<section id="физические-параметры-5" class="level3">
<h3 class="anchored" data-anchor-id="физические-параметры-5">Физические параметры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Параметр</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Вес (сухой)</td>
<td style="text-align: left;"><strong>~370 кг</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Вес на Меркурии</td>
<td style="text-align: left;">140 кг (ощущаемый)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Габариты</td>
<td style="text-align: left;">1.8 × 1.2 × 1.5 м</td>
</tr>
</tbody>
</table>
</section>
<section id="состав-материалов-5" class="level3">
<h3 class="anchored" data-anchor-id="состав-материалов-5">Состав материалов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Источник</th>
<th style="text-align: left;">Масса</th>
<th style="text-align: left;">Соотношение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Локальные ресурсы</td>
<td style="text-align: left;">~355 кг</td>
<td style="text-align: left;">24</td>
</tr>
<tr class="even">
<td style="text-align: left;">«Витамины» (импорт)</td>
<td style="text-align: left;">~15 кг</td>
<td style="text-align: left;">1</td>
</tr>
</tbody>
</table>
<p><strong>Витамины:</strong> - Радиационно-стойкий CPU - Оптические сенсоры (стереокамеры) - Прецизионные сервоприводы (запястья и пальцы) - Обмотки электромоторов - Капсулы со смазкой</p>
<p><strong>Локальные материалы (оптимизированный гибрид Fe/Al):</strong> - <strong>Алюминиевая рама шасси</strong> (100 кг) — лёгкость - <strong>Стальные колёса + оси</strong> (60 кг) — абразивостойкость (критично) - Стальные подшипники и узлы (20 кг) - <strong>Алюминиевые руки-манипуляторы</strong> (80 кг) — точность, лёгкость - NaS-батарея (45 кг) - <strong>Алюминиевые радиаторы и панели</strong> (50 кг) — теплоотвод</p>
<p><strong>Соотношение:</strong> ~22% сталь, ~62% алюминий (больше Al — нужны лёгкие точные руки)</p>
</section>
<section id="сенсоры-5" class="level3">
<h3 class="anchored" data-anchor-id="сенсоры-5">Сенсоры</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Тип</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Визуальные</td>
<td style="text-align: left;">Стереопара камер на выдвижной штанге за кварцевым блоком</td>
</tr>
<tr class="even">
<td style="text-align: left;">Тактильные</td>
<td style="text-align: left;">Датчики усилия в захватах</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Позиционирование</td>
<td style="text-align: left;">Энкодеры во всех суставах</td>
</tr>
</tbody>
</table>
</section>
<section id="конструкция-5" class="level3">
<h3 class="anchored" data-anchor-id="конструкция-5">Конструкция</h3>
<p><strong>Шасси:</strong> - Шестиколёсный ровер с независимой подвеской - <strong>Стальная рама</strong>, характерная текстура WAAM-печати, тёмно-серая - Клиренс: 0.3 м</p>
<p><strong>Торс:</strong> - <strong>Алюминиевый цилиндр</strong> с поворотной платформой — теплоотвод - Крепление на шасси через стальной подшипник</p>
<p><strong>Манипуляторы:</strong> - 2 руки, по 5 степеней свободы (против 7 у Кентавра-З) - <strong>Алюминиевые трубы</strong> с текстурой 3D-печати — требуется лёгкость для точности - Защита суставов: алюминиевая чешуя - Стальные шарниры в нагруженных точках - Захваты: упрощённые 3-пальцевые (против 5-пальцевых)</p>
<p><strong>Особенность:</strong> Гибридная конструкция Fe/Al. Стальное шасси для прочности, алюминиевые руки для точности. Способен выполнять основные сборочные операции: затяжка болтов, сварка WAAM, установка модулей. На каждом заводе нужно <strong>10+ штук</strong> для сборочного стапеля. Работает как внутри купола, так и снаружи.</p>
<hr>
</section>
</section>
<section id="крот-м-mole-m" class="level2">
<h2 class="anchored" data-anchor-id="крот-м-mole-m">Крот-М (Mole-M)</h2>
<p><em>Глубинный шахтёр / Бульдозер</em></p>
<section id="физические-параметры-6" class="level3">
<h3 class="anchored" data-anchor-id="физические-параметры-6">Физические параметры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Параметр</th>
<th style="text-align: left;">Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Вес (сухой)</td>
<td style="text-align: left;"><strong>~1 500 кг</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Вес на Меркурии</td>
<td style="text-align: left;">570 кг (ощущаемый)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Длина</td>
<td style="text-align: left;">3.5 м</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ширина</td>
<td style="text-align: left;">2.8 м</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Высота</td>
<td style="text-align: left;">1.2 м</td>
</tr>
</tbody>
</table>
</section>
<section id="состав-материалов-6" class="level3">
<h3 class="anchored" data-anchor-id="состав-материалов-6">Состав материалов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Источник</th>
<th style="text-align: left;">Масса</th>
<th style="text-align: left;">Соотношение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Локальные ресурсы</td>
<td style="text-align: left;">~1 460 кг</td>
<td style="text-align: left;">36</td>
</tr>
<tr class="even">
<td style="text-align: left;">«Витамины» (импорт)</td>
<td style="text-align: left;">~40 кг</td>
<td style="text-align: left;">1</td>
</tr>
</tbody>
</table>
<p><strong>Витамины:</strong> - Драйверы моторов - Навигационные сенсоры (IMU/лидар) - Вставки из карбида вольфрама (расходники для зубьев)</p>
<p><strong>Локальные материалы (оптимизированный гибрид Fe/Al):</strong> - <strong>Стальные гусеницы</strong> (400 кг) — абразивостойкость критична - <strong>Стальная рама</strong> (400 кг) — только несущая основа - <strong>Стальной ковш/отвал</strong> (300 кг) — рабочий орган - Стальные приводы и редукторы (150 кг) - NaS-батарея (натрий-серная, 100 кг) - <strong>Алюминиевые панели корпуса и радиаторы</strong> (100 кг) — теплоотвод</p>
<p><strong>Соотношение:</strong> ~83% сталь, ~13% алюминий, ~4% прочее (экскаватору нужна масса для тяги)</p>
</section>
<section id="сенсоры-6" class="level3">
<h3 class="anchored" data-anchor-id="сенсоры-6">Сенсоры</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Тип</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Визуальные</td>
<td style="text-align: left;">Камеры только заднего вида (спереди опасно)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Георадар</td>
<td style="text-align: left;">В днище, сканирует породу под собой</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Вибрация</td>
<td style="text-align: left;">Датчики, определяющие твёрдость породы</td>
</tr>
</tbody>
</table>
</section>
<section id="сменные-модули-5" class="level3">
<h3 class="anchored" data-anchor-id="сменные-модули-5">Сменные модули</h3>
<p><strong>Крепление:</strong> Передняя навеска (как у трактора)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Модуль</th>
<th style="text-align: left;">Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Роторный экскаватор</td>
<td style="text-align: left;">Барабан с ковшами</td>
</tr>
<tr class="even">
<td style="text-align: left;">Бульдозерный отвал</td>
<td style="text-align: left;">Для расчистки</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Гидромолот</td>
<td style="text-align: left;">Пневмоударник для дробления скал</td>
</tr>
</tbody>
</table>
</section>
<section id="конструкция-6" class="level3">
<h3 class="anchored" data-anchor-id="конструкция-6">Конструкция</h3>
<p><strong>Шасси:</strong> - Широкая гусеничная база (как у бульдозера) - Длина: 3.5 м, ширина траков: 0.8 м - Гусеницы скелетного типа (открытые, самоочистка) - Материал: <strong>литая сталь</strong> (абразивостойкость критична)</p>
<p><strong>Корпус:</strong> - Приземистый обтекаемый короб - Высота: 1.2 м - Материал: <strong>алюминиевые панели</strong> (экономия массы)</p>
<p><strong>Инструмент:</strong> - Огромный отвал спереди или рыхлитель сзади - Ширина отвала: 3.5 м - <strong>Стальной</strong> — полированный от трения</p>
<p><strong>Защита:</strong> - Оси под стальными крышками - Лидар за толстой кварцевой щелью</p>
<p><strong>Особенность:</strong> Преимущественно стальная конструкция (~83% Fe). Масса ~1.5 т обеспечивает достаточную тягу при копании на Меркурии (570 кг ощущаемый вес при 0.38g). Алюминий используется для теплоотвода (панели корпуса) — экономия материала для зеркал. Абразивостойкость критична для гусениц и ковша — сталь единственный вариант.</p>
<hr>
</section>
</section>
<section id="операционная-модель-крот-м" class="level2">
<h2 class="anchored" data-anchor-id="операционная-модель-крот-м">Операционная модель Крот-М</h2>
<section id="проблема-энергопитание-при-88-суточной-ночи" class="level3">
<h3 class="anchored" data-anchor-id="проблема-энергопитание-при-88-суточной-ночи">Проблема: энергопитание при 88-суточной ночи</h3>
<p>NaS-батареи требуют постоянного подогрева до +300°C, потребляя 5–10 кВт (<a href="../../ru/science/risks.html#4-ресурс-nas-батарей-в-ночной-период">Риски #4</a>). При ёмкости батареи 10–15 кВт·ч робот разрядится на самоподогрев за 1–2 часа.</p>
<p><strong>Гибернация отвергнута:</strong> NaS-батарея при охлаждении ниже +280°C необратимо деградирует (кристаллизация электролита).</p>
</section>
<section id="физика-терминатора-меркурия" class="level3">
<h3 class="anchored" data-anchor-id="физика-терминатора-меркурия">Физика терминатора Меркурия</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Параметр</th>
<th>Значение</th>
<th>Источник</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Скорость терминатора</td>
<td><strong>~3 м/с</strong> (10.9 км/час)</td>
<td>Расчёт: 15,329 км экватор / 58.6 сут (<a href="https://nssdc.gsfc.nasa.gov/planetary/factsheet/mercuryfact.html">NASA Mercury Fact Sheet</a>)</td>
</tr>
<tr class="even">
<td>Температура на терминаторе</td>
<td><strong>0–100°C</strong></td>
<td>Экстраполяция: −180°C тень, +430°C солнце</td>
</tr>
<tr class="odd">
<td>Ширина комфортной зоны</td>
<td>~10–20 км</td>
<td>Оценка: при 3 м/с = 1–2 часа смещения</td>
</tr>
</tbody>
</table>
<p><strong>Вывод:</strong> Терминатор движется медленнее пешехода. Роботы могут «следовать» за ним или работать в его зоне длительное время.</p>
</section>
<section id="рекомендованное-решение-гибрид-кабель-батарея" class="level3">
<h3 class="anchored" data-anchor-id="рекомендованное-решение-гибрид-кабель-батарея">Рекомендованное решение: ГИБРИД (кабель + батарея)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 45%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Режим</th>
<th>Доля времени</th>
<th>Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Кабельное питание</td>
<td>90%</td>
<td>6 Кротов на кабелях, радиус 10–15 км от завода</td>
</tr>
<tr class="even">
<td>Автономные вылазки</td>
<td>10%</td>
<td>Отцепка для разведки, 30–60 мин на батарее</td>
</tr>
</tbody>
</table>
<p><strong>Эффективность:</strong> ~80% (vs 40% у челночного режима без кабеля).</p>
</section>
<section id="параметры-кабельной-системы" class="level3">
<h3 class="anchored" data-anchor-id="параметры-кабельной-системы">Параметры кабельной системы</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Параметр</th>
<th>Значение</th>
<th>Источник / Расчёт</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Длина кабеля</td>
<td>10 км</td>
<td>Максимум при потерях &lt;5%</td>
</tr>
<tr class="even">
<td>Напряжение</td>
<td>10 кВ</td>
<td>Стандарт силовых кабелей в вакууме</td>
</tr>
<tr class="odd">
<td>Сечение (Al)</td>
<td>9 мм²</td>
<td>S = (ρ × L × I) / (U × 0.05), где ρ_Al = 2.8×10⁻⁸ Ом·м</td>
</tr>
<tr class="even">
<td>Масса кабеля</td>
<td>~350 кг</td>
<td>9 мм² × 10 км × 2.7 г/см³ + изоляция</td>
</tr>
<tr class="odd">
<td>Барабан + мотор</td>
<td>~200 кг</td>
<td>Оценка</td>
</tr>
<tr class="even">
<td><strong>Масса системы</strong></td>
<td><strong>~550 кг</strong></td>
<td>Сумма</td>
</tr>
<tr class="odd">
<td>Потери на 10 км</td>
<td>~0.7%</td>
<td>P_loss = I²R при 10 кВ, 8 кВт нагрузка</td>
</tr>
</tbody>
</table>
<p><strong>Производство:</strong> Кабель из местного алюминия (<a href="../../ru/science/factory.html#этап-1-mre">Завод — Этап 1</a>), изоляция — силикатное волокно (<a href="../../ru/science/factory.html#этап-8-стекло-и-керамика">Завод — Керамика</a>), барабаны — сталь.</p>
</section>
<section id="схема-добычи-комбинированная" class="level3">
<h3 class="anchored" data-anchor-id="схема-добычи-комбинированная">Схема добычи: комбинированная</h3>
<p><strong>Фаза 1: Поверхностная (основная)</strong> - Крот снимает верхний слой реголита (0.5–1 м) - Движение радиальными полосами от завода - Кабель укладывается на землю за роботом - После выработки полосы — смещение на соседний сектор</p>
<p><strong>Фаза 2: Карьерная (в богатых зонах)</strong> - Георадар находит зону с высоким содержанием Al/Fe - Крот отцепляется от кабеля - Копает вглубь на батарее (30–60 мин) - Возвращается к кабелю для подзарядки</p>
<p><strong>Секторная схема:</strong> 6 секторов по 60°, по 1 Кроту на сектор.</p>
</section>
<section id="масштабируемость-1000-заводов" class="level3">
<h3 class="anchored" data-anchor-id="масштабируемость-1000-заводов">Масштабируемость (1000 заводов)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Параметр</th>
<th>На 1 завод</th>
<th>На 1000 заводов</th>
<th>Источник</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Кроты-добытчики</td>
<td>6</td>
<td>6,000</td>
<td><a href="../../ru/science/calculations/railgun.html">Масс-драйвер</a></td>
</tr>
<tr class="even">
<td>Резерв (+20%)</td>
<td>1</td>
<td>1,000</td>
<td>Стандартный запас</td>
</tr>
<tr class="odd">
<td><strong>Итого Кротов</strong></td>
<td><strong>7</strong></td>
<td><strong>7,000</strong></td>
<td></td>
</tr>
<tr class="even">
<td>Масса кабеля</td>
<td>350 кг</td>
<td>3,500 т</td>
<td>Расчёт выше</td>
</tr>
<tr class="odd">
<td>Время производства</td>
<td>—</td>
<td><strong>~1 час</strong></td>
<td>90,000 т Al/день (<a href="../../ru/science/calculations/energy.html">Энергия</a>)</td>
</tr>
</tbody>
</table>
<p><strong>Вывод:</strong> Кабельная инфраструктура для 1000 заводов = 1 час работы всей системы. Масштабируемость не является проблемой.</p>
<hr>
</section>
</section>
<section id="операционная-модель-краб-м" class="level2">
<h2 class="anchored" data-anchor-id="операционная-модель-краб-м">Операционная модель Краб-М</h2>
<section id="проблема-логистика-по-маршрутам-разной-длины" class="level3">
<h3 class="anchored" data-anchor-id="проблема-логистика-по-маршрутам-разной-длины">Проблема: логистика по маршрутам разной длины</h3>
<p>Краб-М — основной логист комплекса. В отличие от Крота (радиальная работа от завода), Краб движется по <strong>маршрутам</strong>: карьер → завод → буфер → масс-драйвер. Маршруты меняются в зависимости от активного карьера.</p>
<p><strong>Почему НЕ кабели:</strong> - Троллейбусная система слишком сложна для пересечённой местности - Маршруты непостоянны (зависят от выработки карьеров) - Нет единой точки привязки как у Крота</p>
</section>
<section id="рекомендованное-решение-зарядные-станции" class="level3">
<h3 class="anchored" data-anchor-id="рекомендованное-решение-зарядные-станции">Рекомендованное решение: ЗАРЯДНЫЕ СТАНЦИИ</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Режим</th>
<th>Доля времени</th>
<th>Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Движение</td>
<td>70%</td>
<td>Перевозка руды/зеркал между точками</td>
</tr>
<tr class="even">
<td>Зарядка</td>
<td>30%</td>
<td>Во время погрузки/разгрузки (10–15 мин)</td>
</tr>
</tbody>
</table>
<p><strong>Принцип:</strong> Краб заряжается <strong>пока ждёт</strong> погрузку или разгрузку. Это не отдельная операция, а совмещённая с логистикой.</p>
</section>
<section id="параметры-системы-питания" class="level3">
<h3 class="anchored" data-anchor-id="параметры-системы-питания">Параметры системы питания</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Параметр</th>
<th>Значение</th>
<th>Источник / Расчёт</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Батарея NaS</td>
<td>80 кг × 100 Вт·ч/кг = <strong>8 кВт·ч</strong></td>
<td><a href="#краб-м-crab-m">Краб-М</a>, <a href="#nas-батареи">NaS</a></td>
</tr>
<tr class="even">
<td>Подогрев NaS</td>
<td>5–10 кВт</td>
<td><a href="../../ru/science/risks.html#4-ресурс-nas-батарей-в-ночной-период">Риски #4</a></td>
</tr>
<tr class="odd">
<td>Мощность движения</td>
<td>~10–15 кВт</td>
<td>Оценка: 1800 кг, 10 км/ч</td>
</tr>
<tr class="even">
<td><strong>Средняя мощность</strong></td>
<td><strong>~20 кВт</strong></td>
<td>Движение + подогрев</td>
</tr>
<tr class="odd">
<td>Автономия на заряде</td>
<td>~24 мин</td>
<td>8 кВт·ч / 20 кВт</td>
</tr>
<tr class="even">
<td>Скорость</td>
<td>~10 км/ч</td>
<td>По аналогии с земной карьерной техникой</td>
</tr>
<tr class="odd">
<td><strong>Дальность на заряде</strong></td>
<td><strong>~4 км</strong></td>
<td>24 мин × 10 км/ч</td>
</tr>
</tbody>
</table>
<p><strong>Критично:</strong> Дальность 4 км &lt; расстояние карьер-завод (5–15 км). Требуются промежуточные станции.</p>
</section>
<section id="схема-зарядной-сети" class="level3">
<h3 class="anchored" data-anchor-id="схема-зарядной-сети">Схема зарядной сети</h3>
<pre><code>          [Карьер 1]────┐
          [Карьер 2]────┼──⚡── [ЗАВОД] ──⚡── [Буфер] ──⚡── [МД]
          [Карьер 3]────┘
                         │
              ⚡ промежуточные станции на трассах (каждые 3 км)</code></pre>
</section>
<section id="инфраструктура-зарядных-станций" class="level3">
<h3 class="anchored" data-anchor-id="инфраструктура-зарядных-станций">Инфраструктура зарядных станций</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Локация</th>
<th>Станций</th>
<th>Назначение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Завод (вход/выход)</td>
<td>4</td>
<td>Основная точка</td>
</tr>
<tr class="even">
<td>Буфер масс-драйвера</td>
<td>2</td>
<td>Промежуточная</td>
</tr>
<tr class="odd">
<td>Вход масс-драйвера</td>
<td>2</td>
<td>Финальная точка</td>
</tr>
<tr class="even">
<td>Трасса к карьерам</td>
<td>4–5</td>
<td>Каждые 3 км по маршрутам</td>
</tr>
<tr class="odd">
<td><strong>Итого на комплекс</strong></td>
<td><strong>~12–15</strong></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="время-цикла-с-зарядкой" class="level3">
<h3 class="anchored" data-anchor-id="время-цикла-с-зарядкой">Время цикла с зарядкой</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Маршрут</th>
<th>Расстояние</th>
<th>Езда</th>
<th>Зарядок</th>
<th>Время цикла</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Карьер → Завод</td>
<td>10 км</td>
<td>60 мин</td>
<td>3 × 10 мин</td>
<td><strong>90 мин</strong></td>
</tr>
<tr class="even">
<td>Завод → Буфер → МД</td>
<td>4 км</td>
<td>24 мин</td>
<td>1 × 10 мин</td>
<td><strong>34 мин</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="количество-крабов-м-на-комплекс" class="level3">
<h3 class="anchored" data-anchor-id="количество-крабов-м-на-комплекс">Количество Крабов-М на комплекс</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Задача</th>
<th>Крабов</th>
<th>Расчёт</th>
<th>Источник</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Транспорт руды</td>
<td>4</td>
<td>270 т/день ÷ 70 т/рейс, 2 рейса/день</td>
<td><a href="../../ru/science/calculations/railgun.html">Масс-драйвер</a></td>
</tr>
<tr class="even">
<td>Транспорт зеркал</td>
<td>4</td>
<td>90 т/день ÷ 15 т/рейс, 6 рейсов</td>
<td><a href="../../ru/science/calculations/railgun.html">Масс-драйвер</a></td>
</tr>
<tr class="odd">
<td>Подача на пусковую</td>
<td>4</td>
<td>Непрерывно, каждые 2.4 мин</td>
<td><a href="../../ru/science/calculations/railgun.html">Масс-драйвер</a></td>
</tr>
<tr class="even">
<td>Сбор графита</td>
<td>2</td>
<td>Сбор контейнеров с мини МД</td>
<td><a href="../../ru/science/calculations/regolith-processing.html#логистика-графита-комплексы-карбон">Логистика графита</a></td>
</tr>
<tr class="odd">
<td>Резерв (+20%)</td>
<td>3</td>
<td>Стандартный запас</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Итого</strong></td>
<td><strong>17</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="логистика-графита-комплексы-карбон" class="level3">
<h3 class="anchored" data-anchor-id="логистика-графита-комплексы-карбон">Логистика графита (комплексы Карбон)</h3>
<p>Графит доставляется на полюс баллистически (мини масс-драйверы с комплексов Карбон-Север и Карбон-Юг). Крабы-М собирают контейнеры.</p>
<p><strong>Параметры:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Параметр</th>
<th>Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Контейнеров/день</td>
<td>~100</td>
</tr>
<tr class="even">
<td>Масса контейнера</td>
<td>~100 кг</td>
</tr>
<tr class="odd">
<td>Зона приёма</td>
<td>Сетка-ловушка 500×500 м</td>
</tr>
<tr class="even">
<td>Крабов-сборщиков</td>
<td>2</td>
</tr>
</tbody>
</table>
<p><strong>Цикл сбора:</strong></p>
<ol type="1">
<li>Контейнер приземляется в зоне приёма (сетка тормозит, не даёт отскочить)</li>
<li>Краб-М подъезжает, загружает контейнер (манипулятор)</li>
<li>Везёт на склад графита у завода</li>
<li>Возвращается к следующему контейнеру</li>
</ol>
<p><strong>Примечание:</strong> Контейнеры прилетают с интервалом ~15 мин. Два Краба-М справляются с потоком.</p>
<hr>
</section>
</section>
<section id="операционная-модель-кентавр-м" class="level2">
<h2 class="anchored" data-anchor-id="операционная-модель-кентавр-м">Операционная модель Кентавр-М</h2>
<section id="проблема-работа-в-двух-зонах" class="level3">
<h3 class="anchored" data-anchor-id="проблема-работа-в-двух-зонах">Проблема: работа в двух зонах</h3>
<p>Кентавр-М — сборщик и техник. Работает в <strong>двух принципиально разных зонах</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Зона</th>
<th>Доля времени</th>
<th>Условия</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Внутри купола</td>
<td>70%</td>
<td>Защита от радиации, стабильная температура</td>
</tr>
<tr class="even">
<td>Снаружи</td>
<td>30%</td>
<td>Вакуум, перепады температур, обслуживание МД</td>
</tr>
</tbody>
</table>
</section>
<section id="рекомендованное-решение-кабель-автономия" class="level3">
<h3 class="anchored" data-anchor-id="рекомендованное-решение-кабель-автономия">Рекомендованное решение: КАБЕЛЬ + АВТОНОМИЯ</h3>
<p><strong>Внутри купола (кабель 50 м):</strong> - Короткий кабель на барабане - Подключение к силовой шине купола - Полная свобода передвижения в рабочей зоне - Неограниченное время работы</p>
<p><strong>Снаружи (батарея + станции):</strong> - Автономная работа на батарее (40–100 мин) - Зарядные станции у шлюза и на масс-драйвере - Вахтовый режим: один работает, другой заряжается</p>
</section>
<section id="параметры-системы-питания-1" class="level3">
<h3 class="anchored" data-anchor-id="параметры-системы-питания-1">Параметры системы питания</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Параметр</th>
<th>Значение</th>
<th>Источник / Расчёт</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Масса робота</td>
<td>450 кг</td>
<td><a href="#кентавр-м-centaur-m">Кентавр-М</a></td>
</tr>
<tr class="even">
<td>Батарея NaS</td>
<td>50 кг × 100 Вт·ч/кг = <strong>5 кВт·ч</strong></td>
<td><a href="#кентавр-м-centaur-m">Кентавр-М</a>, <a href="#nas-батареи">NaS</a></td>
</tr>
<tr class="odd">
<td>Подогрев NaS</td>
<td>3–5 кВт</td>
<td>Пропорционально: 50/100 × 5–10 кВт</td>
</tr>
<tr class="even">
<td>Сварка WAAM</td>
<td>~3 кВт</td>
<td><a href="../../ru/science/factory.html#этап-5-waam">Завод — WAAM</a></td>
</tr>
<tr class="odd">
<td><strong>Мощность работы</strong></td>
<td><strong>~8 кВт</strong></td>
<td>Сварка + манипуляторы + подогрев</td>
</tr>
<tr class="even">
<td>Мощность ожидания</td>
<td>~3 кВт</td>
<td>Только подогрев NaS</td>
</tr>
<tr class="odd">
<td><strong>Автономия (работа)</strong></td>
<td><strong>~40 мин</strong></td>
<td>5 кВт·ч / 8 кВт</td>
</tr>
<tr class="even">
<td>Автономия (ожидание)</td>
<td>~100 мин</td>
<td>5 кВт·ч / 3 кВт</td>
</tr>
</tbody>
</table>
</section>
<section id="схема-работы-снаружи-вахтовый-режим" class="level3">
<h3 class="anchored" data-anchor-id="схема-работы-снаружи-вахтовый-режим">Схема работы снаружи (вахтовый режим)</h3>
<pre><code>[КУПОЛ]──⚡──[Кентавр A работает на МД]
    │
    └──⚡──[Кентавр B заряжается у шлюза]
              │
              └──через 40 мин──►  [меняются]</code></pre>
</section>
<section id="кабельная-система-внутри-купола" class="level3">
<h3 class="anchored" data-anchor-id="кабельная-система-внутри-купола">Кабельная система внутри купола</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Параметр</th>
<th>Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Точек подключения</td>
<td>8–10 (по периметру цеха)</td>
</tr>
<tr class="even">
<td>Длина кабеля</td>
<td>50 м</td>
</tr>
<tr class="odd">
<td>Напряжение</td>
<td>400 В DC (безопасно внутри)</td>
</tr>
<tr class="even">
<td>Сечение</td>
<td>4 мм² Al</td>
</tr>
<tr class="odd">
<td>Масса кабеля</td>
<td>~10 кг</td>
</tr>
<tr class="even">
<td>Барабан</td>
<td>~5 кг</td>
</tr>
</tbody>
</table>
</section>
<section id="зарядные-станции-снаружи" class="level3">
<h3 class="anchored" data-anchor-id="зарядные-станции-снаружи">Зарядные станции снаружи</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Локация</th>
<th>Станций</th>
<th>Назначение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Шлюз купола</td>
<td>2</td>
<td>Перед/после вылазки</td>
</tr>
<tr class="even">
<td>Вход масс-драйвера</td>
<td>2</td>
<td>Обслуживание МД</td>
</tr>
<tr class="odd">
<td>Солнечные панели</td>
<td>2</td>
<td>Обслуживание энергосистемы</td>
</tr>
<tr class="even">
<td><strong>Итого</strong></td>
<td><strong>6</strong></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="распределение-кентавров-м-по-зонам" class="level3">
<h3 class="anchored" data-anchor-id="распределение-кентавров-м-по-зонам">Распределение Кентавров-М по зонам</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 28%">
<col style="width: 34%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Зона</th>
<th>Кентавров</th>
<th>Тип питания</th>
<th>Задачи</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Производство (внутри)</td>
<td>15</td>
<td>Кабель 50 м</td>
<td>Плавка, прокат, сборка</td>
</tr>
<tr class="even">
<td>Обслуживание МД</td>
<td>4</td>
<td>Батарея + станции</td>
<td>Техник, ремонт направляющих</td>
</tr>
<tr class="odd">
<td>Шлюз / снаружи</td>
<td>2</td>
<td>Батарея + станции</td>
<td>Разное</td>
</tr>
<tr class="even">
<td>Резерв (+10%)</td>
<td>2</td>
<td>—</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Итого</strong></td>
<td><strong>23</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="сводка-энергоснабжение-всех-gen-2-роботов" class="level2">
<h2 class="anchored" data-anchor-id="сводка-энергоснабжение-всех-gen-2-роботов">Сводка: энергоснабжение всех Gen-2 роботов</h2>
<section id="таблица-решений" class="level3">
<h3 class="anchored" data-anchor-id="таблица-решений">Таблица решений</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 31%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Робот</th>
<th>Решение</th>
<th>Обоснование</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Крот-М</strong></td>
<td>Кабель 10 км + автономия</td>
<td>Радиальная работа от завода</td>
</tr>
<tr class="even">
<td><strong>Краб-М</strong></td>
<td>Зарядные станции</td>
<td>Маршрутная логистика, переменные пути</td>
</tr>
<tr class="odd">
<td><strong>Кентавр-М</strong></td>
<td>Кабель 50 м (внутри) + станции (снаружи)</td>
<td>Две зоны работы</td>
</tr>
</tbody>
</table>
</section>
<section id="инфраструктура-на-1-комплекс" class="level3">
<h3 class="anchored" data-anchor-id="инфраструктура-на-1-комплекс">Инфраструктура на 1 комплекс</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Компонент</th>
<th>Количество</th>
<th>Тип</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Кабельные точки (Крот)</td>
<td>6</td>
<td>Высоковольтные (10 кВ)</td>
</tr>
<tr class="even">
<td>Зарядные станции (Краб)</td>
<td>12–15</td>
<td>Быстрая зарядка</td>
</tr>
<tr class="odd">
<td>Точки внутри купола (Кентавр)</td>
<td>8–10</td>
<td>Низковольтные (400 В)</td>
</tr>
<tr class="even">
<td>Станции снаружи (Кентавр)</td>
<td>6</td>
<td>Быстрая зарядка</td>
</tr>
<tr class="odd">
<td><strong>Итого</strong></td>
<td><strong>~35–37</strong></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="пересчёт-количества-роботов" class="level3">
<h3 class="anchored" data-anchor-id="пересчёт-количества-роботов">Пересчёт количества роботов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Робот</th>
<th>Ранее</th>
<th>Пересчёт</th>
<th>Изменение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Крот-М</td>
<td>6</td>
<td>7</td>
<td>+1 (резерв)</td>
</tr>
<tr class="even">
<td>Краб-М</td>
<td>10</td>
<td>14</td>
<td>+4 (зарядка)</td>
</tr>
<tr class="odd">
<td>Кентавр-М</td>
<td>21</td>
<td>23</td>
<td>+2 (вахты снаружи)</td>
</tr>
<tr class="even">
<td><strong>Итого на комплекс</strong></td>
<td><strong>48</strong></td>
<td><strong>~52</strong></td>
<td><strong>+4</strong></td>
</tr>
<tr class="odd">
<td>С общим резервом 20%</td>
<td>58</td>
<td><strong>~62</strong></td>
<td>+4</td>
</tr>
</tbody>
</table>
<p><strong>Подробности инфраструктуры:</strong> <a href="../../ru/science/factory.html#кабельная-инфраструктура-добычи">Завод — Кабельная инфраструктура</a></p>
<hr>
</section>
</section>
</section>
<section id="монтажная-бригада-the-landing-party" class="level1">
<h1>Монтажная Бригада (The Landing Party)</h1>
<p><em>Первая Экспедиция — спецназ робототехники.</em></p>
<p>В отличие от миллионов роботов, которые будут <em>произведены</em> на Меркурии (дешёвых и массовых), эти роботы — <strong>элита</strong>. Собраны на Земле из лучших материалов, с герметичными приводами на «сухой» смазке (золото/молибден). Рассчитаны на работу в вакууме <em>до</em> того, как будет построен защитный купол.</p>
<p>Их задача — построить завод и… умереть (быть переплавленными), так как их ресурс ограничен.</p>
<p><strong>Груз:</strong> ~55 тонн (роботы + ремкомплект + оборудование).</p>
<p><strong>Срок сборки:</strong> 7 дней («блиц-монтаж»). Больше роботов = быстрее + резерв на поломки.</p>
<hr>
<section id="пауки-16" class="level3">
<h3 class="anchored" data-anchor-id="пауки-16">Пауки × 16</h3>
<p><em>Самые первые.</em></p>
<ul>
<li><strong>Зачем везём:</strong> Только они могут залезть на отвесные скалы («Пики света»), куда не заедет колёсная техника</li>
<li><strong>Задача №1:</strong> В первые 24 часа после посадки затащить на вершины гор кабели и развернуть там солнечные вышки. Без них база останется без энергии и замёрзнет</li>
<li><strong>Судьба:</strong> Остаются на скалах как инспекторы и ретрансляторы связи</li>
</ul>
</section>
<section id="крабы-12" class="level3">
<h3 class="anchored" data-anchor-id="крабы-12">Крабы × 12</h3>
<p><em>Тяжёлая сила.</em></p>
<ul>
<li><strong>Зачем везём:</strong> Нужно выгрузить из корабля модули весом по 5–10 тонн (Солнечную печь, станки, свёрнутый купол). «Кентавр» такой вес не поднимет</li>
<li><strong>Задача №1:</strong> Выгрузка</li>
<li><strong>Задача №2:</strong> Расчистка площадки (работают как бульдозеры)</li>
<li><strong>Задача №3:</strong> Затаскивание станков внутрь надутого купола</li>
</ul>
</section>
<section id="кентавры-24" class="level3">
<h3 class="anchored" data-anchor-id="кентавры-24">Кентавры × 24</h3>
<p><em>Интеллект и руки.</em></p>
<ul>
<li><strong>Зачем везём:</strong> Единственные роботы, способные выполнять сложные операции (крутить болты, соединять разъёмы, варить)</li>
<li><strong>Задача:</strong> Сборка всей инфраструктуры. Подключают кабели, крепят купол к грунту, собирают производственную линию внутри цеха</li>
<li><strong>Важно:</strong> Первое время работают в режиме <strong>Аватара</strong> — ими управляют операторы с Земли (в VR-шлемах), чтобы исключить ошибки ИИ при монтаже уникального оборудования</li>
</ul>
</section>
<section id="кроты-4" class="level3">
<h3 class="anchored" data-anchor-id="кроты-4">Кроты × 4</h3>
<p><em>Добытчики.</em></p>
<ul>
<li><strong>Зачем везём:</strong> Чтобы запустить печь, нужно сырьё</li>
<li><strong>Задача:</strong> Сразу после установки печи начинают грызть грунт и подавать его на конвейер</li>
<li><strong>Особенность:</strong> Везём мало, потому что это самые простые роботы — их проще всего начать печатать на месте первыми</li>
</ul>
<hr>
</section>
<section id="кого-не-везём" class="level3">
<h3 class="anchored" data-anchor-id="кого-не-везём">Кого НЕ везём</h3>
<ul>
<li><strong>Скатов (Чистильщиков):</strong> На первом этапе пыль с зеркал будут смахивать «Пауки» или «Кентавры». Специализированные уборщики появятся позже, когда зеркал станут тысячи</li>
<li><strong>Массовых Кротов:</strong> Везём только 4 штуки для старта. Остальные тысячи будут сделаны уже там, из местной стали</li>
</ul>
<hr>
</section>
<section id="визуализация-высадки" class="level3">
<h3 class="anchored" data-anchor-id="визуализация-высадки">Визуализация высадки</h3>
<blockquote class="blockquote">
<p>Представьте высадку не как парад, а как муравейник.</p>
<p>Люки открываются. Первыми высыпают юркие «Пауки» с катушками кабеля и бегут вверх по склонам кратера. Затем выползают тяжёлые «Крабы», таща за собой тюки с надувным куполом. «Кентавры» суетятся вокруг, соединяя шланги и кабели.</p>
<p>Всё это происходит в абсолютной тишине вакуума, под жёстким светом звёзд и длинными чёрными тенями.</p>
</blockquote>
<hr>
</section>
<section id="итого-56-роботов" class="level3">
<h3 class="anchored" data-anchor-id="итого-56-роботов">Итого: 56 роботов</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Тип</th>
<th style="text-align: center;">Количество</th>
<th style="text-align: left;">Главная задача</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Пауки</td>
<td style="text-align: center;">16</td>
<td style="text-align: left;">Включить свет (кабели + зеркала на пики)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Крабы</td>
<td style="text-align: center;">12</td>
<td style="text-align: left;">Выгрузка модулей, расчистка, логистика</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Кентавры</td>
<td style="text-align: center;">24</td>
<td style="text-align: left;">Сборка завода (стыковка модулей)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Кроты</td>
<td style="text-align: center;">4</td>
<td style="text-align: left;">Первая руда</td>
</tr>
</tbody>
</table>
<p><strong>Почему больше:</strong> Срок сборки сокращён с 30 до 7 дней. Больше роботов = параллельная работа + резерв на поломки.</p>
<hr>
</section>
</section>
<section id="известные-ограничения-роботов" class="level1">
<h1>Известные ограничения роботов</h1>
<blockquote class="blockquote">
<p><strong>Внимание:</strong> Этот раздел описывает проблемы, специфичные для роботов. Общий анализ рисков проекта: <strong><a href="../../ru/science/risks.html">Риски и ограничения</a></strong>.</p>
</blockquote>
<section id="высокие-проблемы" class="level2">
<h2 class="anchored" data-anchor-id="высокие-проблемы">Высокие проблемы</h2>
<section id="смазка-при-430c" class="level3">
<h3 class="anchored" data-anchor-id="смазка-при-430c">1. Смазка при +430°C</h3>
<p>Роботы на солнечной стороне Меркурия работают при экстремальных температурах.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Смазка</th>
<th>Рабочий диапазон</th>
<th>Проблема</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MoS₂ (дисульфид молибдена)</td>
<td>до +350°C</td>
<td>Деградирует при +430°C</td>
</tr>
<tr class="even">
<td>Мягкие металлы (Pb, Au)</td>
<td>до +500°C</td>
<td>Дорогие, быстро изнашиваются</td>
</tr>
<tr class="odd">
<td>Жидкие масла</td>
<td>до +250°C</td>
<td>Испаряются в вакууме</td>
</tr>
</tbody>
</table>
<p><strong>Последствия:</strong> Подшипники и суставы быстро изнашиваются при работе на солнце.</p>
<p><strong>Возможные решения:</strong> - Работа только в тени или полутени (ограничивает зону операций) - Керамические подшипники без смазки (дорогие, хрупкие) - Сплавы золота с индием (Au-In) — до +600°C, но редкие</p>
</section>
<section id="тепловой-режим-nas-батарей" class="level3">
<h3 class="anchored" data-anchor-id="тепловой-режим-nas-батарей">2. Тепловой режим NaS-батарей</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Параметр</th>
<th>Значение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Рабочая температура</td>
<td>300–350°C</td>
</tr>
<tr class="even">
<td>Мощность подогрева</td>
<td>5–10 кВт на батарею</td>
</tr>
<tr class="odd">
<td>Длительность «ночи» Меркурия</td>
<td>88 земных суток</td>
</tr>
</tbody>
</table>
<p><strong>Проблема:</strong> В «ночь» батареи охлаждаются до −180°C. Для поддержания рабочей температуры нужен подогрев из запасённой энергии — но батарея разряжается на самоподогрев.</p>
<p><strong>Возможные решения:</strong> - Гибернация роботов на ночь (отключение, консервация) - Центральные станции подогрева (роботы «паркуются» и подключаются к сети) - Радиоизотопные нагреватели (РИТЭГ) — масса, радиация</p>
</section>
<section id="вероятность-отказов-недооценена" class="level3">
<h3 class="anchored" data-anchor-id="вероятность-отказов-недооценена">3. Вероятность отказов недооценена</h3>
<p>Планируется 56 роботов на первую экспедицию с резервом ~30%.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Фактор</th>
<th>Риск</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Абразивная пыль</td>
<td>Засорение суставов, камер</td>
</tr>
<tr class="even">
<td>Радиация</td>
<td>Сбои CPU, деградация сенсоров</td>
</tr>
<tr class="odd">
<td>Термоциклирование</td>
<td>Усталость материалов (−180°C ↔︎ +430°C)</td>
</tr>
<tr class="even">
<td>Микрометеориты</td>
<td>Повреждение оптики, корпусов</td>
</tr>
</tbody>
</table>
<p><strong>Реальная оценка:</strong> Нужен резерв +50–70% вместо +30%.</p>
<p><strong>Рекомендация:</strong> Увеличить первую партию до 70–80 роботов или иметь запасные модули для ремонта.</p>
</section>
</section>
<section id="требуют-исследования" class="level2">
<h2 class="anchored" data-anchor-id="требуют-исследования">Требуют исследования</h2>
<section id="пылезащита-в-вакууме" class="level3">
<h3 class="anchored" data-anchor-id="пылезащита-в-вакууме">4. Пылезащита в вакууме</h3>
<p>На Луне пыль — главная проблема (Apollo). На Меркурии хуже: - Пыль электростатически заряжена - Нет воздуха для сдувания - Острые частицы режут уплотнения</p>
<p><strong>Требует:</strong> Электростатические экраны, лабиринтные уплотнения, регулярная очистка.</p>
</section>
<section id="автономность-при-670-секундной-задержке" class="level3">
<h3 class="anchored" data-anchor-id="автономность-при-670-секундной-задержке">5. Автономность при 670-секундной задержке</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Режим</th>
<th>Описание</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Аватар (телеуправление)</td>
<td>Невозможно в реальном времени</td>
</tr>
<tr class="even">
<td>Автономный</td>
<td>Требует продвинутого ИИ</td>
</tr>
<tr class="odd">
<td>Гибридный</td>
<td>ИИ действует, человек утверждает</td>
</tr>
</tbody>
</table>
<p><strong>Проблема:</strong> При аварии робот должен сам принять решение за секунды, не дожидаясь команды с Земли.</p>
<p><strong>Требует:</strong> Локальные ИИ-агенты, протоколы аварийного поведения, mesh-сеть между роботами.</p>
</section>
<section id="ремонтопригодность-gen-1" class="level3">
<h3 class="anchored" data-anchor-id="ремонтопригодность-gen-1">6. Ремонтопригодность Gen-1</h3>
<p>Роботы Gen-1 спроектированы для минимальной массы, не для ремонта: - Герметичные моторы (не разбираются) - Клеёные соединения (не раскручиваются) - Специализированные запчасти (не взаимозаменяемы)</p>
<p><strong>Последствия:</strong> При серьёзной поломке робот списывается целиком.</p>
<p><strong>Компромисс:</strong> Принято в проекте — Gen-1 расходные, переплавляются после выработки ресурса. Gen-2 ремонтопригодны.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/DmitryNasikanov\.github\.io\/infinite-energy\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>